CREATE OR REPLACE STREAM TAXI.SILVER.SILVER_TAXI_TRIPS_STREAM
ON TABLE TAXI.TAXI.SILVER_TAXI_TRIPS;


CREATE OR REPLACE TASK TAXI.GOLD.TASK_LOAD_DIM_LOCATION
WAREHOUSE = TAXI
WHEN
    SYSTEM$STREAM_HAS_DATA('TAXI.SILVER.SILVER_TAXI_TRIPS_STREAM')
AS
    CALL SYSTEM$RUN_DBT_TASK(
        'dim_location'
    );


CREATE OR REPLACE TASK TAXI.GOLD.TASK_LOAD_FACT_TAXI
WAREHOUSE = TAXI
AFTER TAXI.GOLD.TASK_LOAD_DIM_LOCATION
AS
    CALL SYSTEM$RUN_DBT_TASK(
        'fact_taxi_trips'
    );


ALTER TASK TAXI.GOLD.TASK_LOAD_DIM_LOCATION RESUME;
ALTER TASK TAXI.GOLD.TASK_LOAD_FACT_TAXI RESUME;
