CREATE OR REPLACE STREAM TAXI.RAW.RAW_TAXI_TRIPS_STREAM
ON TABLE TAXI.RAW.RAW_TAXI_TRIPS
APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK TAXI.SILVER.TASK_LOAD_SILVER_TAXI
WAREHOUSE = TAXI
WHEN
    SYSTEM$STREAM_HAS_DATA('TAXI.RAW.RAW_TAXI_TRIPS_STREAM')
AS
    CALL SYSTEM$RUN_DBT_TASK(
        'silver_taxi_trips'
    );

ALTER TASK TAXI.SILVER.TASK_LOAD_SILVER_TAXI RESUME;
